### ISSUE TITLE
Store member data as JSON in repo and enforce schema

### ISSUE THREAD

**Issue by aaronagray** [Denver-Devs/rolodex#1]
Let's consider the following for data storage:

1. Use JSON as the standard format for members to add themselves via pull request. Something like `member.json` in this repo would do.
2. Enforce a schema according to the (first draft, subject to discussion) schema included below.

This has a few benefits:
1. We could transfer the information in ways that markdown wouldn't allow
2. We could include tests that invoke [json-schema](https://www.npmjs.com/package/jsonschema) to enforce an agreed apon schema.
3. If we do 2, then we could configure CI to automatically fail for PRs that don't match the schema. That way maintainers don't need to waste time validating things by sight. Red or green is easy.

## Example Schema (first draft, subject to discussion)
```
[
  {
    "picture": "http://placehold.it/32x32",
    "website": "https://example.com",
    "name": {
      "first": "Amber",
      "last": "Aguilar"
    },
    "company": "OVIUM",
    "email": "amber.aguilar@ovium.com",
    "pronouns": {
      "personal": "she",
      "object": "her",
      "reflexive": "herself",
      "possessive": "hers"
    },
    "twitter": "example",
    "phone": "+1 (877) 569-3009",
    "about": "Veniam laboris velit quis Lorem fugiat duis velit pariatur minim reprehenderit non et pariatur. Nulla nostrud occaecat occaecat dolore cupidatat qui consequat culpa nulla dolor. Veniam id officia ut sunt laboris Lorem nisi labore sit ut. Excepteur laborum veniam eu cillum quis velit in culpa. Commodo laboris id ipsum veniam cillum culpa nisi.",
    "city": "Denver",
    "state": "CO",
    "skills": [
      "foo",
      "bar",
      "ruby"
    ]
  }
]
```
I generated and saved the above json for editing here: http://beta.json-generator.com/VJMEwtn6l

Edit: Pasted wrong JSON before. Fixed.

**Comment by sreynen** [comment]
I hesitate a bit to make a counter-proposal for fear of adding the very complexity I think we should avoid, but just to follow up on my suggestion in Slack, I think open-schema CSV would maximize ease of participation while still collecting info (vs. losing it to Slack history). That would sacrifice data validity for data quantity.

The request that prompted this was GitHub URLs, which are missing from the example schema. I see one way to add that to a CSV (add a column) and many ways to add that to the JSON schema (new key, turn website into an array, or maybe an object, etc.). I'd favor the simple CSV approach because it puts the emphasis entirely on the data, which seems like the main problem we're trying to solve here. I'd rather see more data that's messy than less data that has been validated.

But because I think the data collection should be the focus here, I also don't want this comment to delay getting there. So if I'm the only CSV advocate, let's just do JSON so we can start collecting data.

**Comment by DrewDahlman** [comment]
I am putting a vote in for JSON.

I do agree with you @sreynen, but also think if we have structured data is the best path as that gives us something consistent to work against so if in the future we decide to add filtering or search we don't have to take into account any misc columns.

**Comment by killtheliterate** [comment]
I mean... we can also solve this with a form, yea? Create the schema, promote ease by making a form that adds new records.

**Comment by DrewDahlman** [comment]
I worry about a form because in order to update things we may need a login system or something, where if we have a JSON file only YOU can modify your info and we check this via PR's

**Comment by toastal** [comment]
This reminds me how bad and fragile JSON can be for this sort of thing. It's computer-friendly, but not user-friendly.

**Comment by toastal** [comment]
Question: why is the top-level an array? Can we be multiple people?

**Comment by killtheliterate** [comment]
What about a form to simply generate a json snip? This can act as a validator, etc. Updating would be fairly simple too.

**Comment by DrewDahlman** [comment]
I could get behind that.

**Comment by LegitTalon** [comment]
I don't want to alarm anyone but github has an API the form could connect to that API and open a PR "Add <first> <last>"

**Comment by aaronagray** [comment]
I think the form-to-json idea is really cool and here are my initial concerns with it:

* It introduces more small problems solve (and thus discussions to have) including hosting (I suspect at http://denverdevs.org/rolodex/new or something), the inevitable CSS someone will have to write, and an endpoint to accept the form request. And then of course something else will come up because code.

* Any changes to the "schema" will require modifying code in two places (presumably here and in the form HTML or Google Doc or Wufoo etc.), and that's not as fun as modifying code in one place. We  could treat the form like the schema definition, but that feels weird because it's not and also my next point. :)

* Forms are hard to get right from an inclusion perspective. For instance, a boolean `male` or `female` field for "gender" will exclude friends of ours in the community. Adding `other` is arguably worse. Similar challenges exist for JSON schemas, but there a sense of permanence associated with a deployed, rendered HTML form that might make others feel unwelcome to contribute to the schema definition itself.

**Comment by DrewDahlman** [comment]
Buut overengineering!

**Comment by aaronagray** [comment]
Exactly. :D That could have been my fourth point. I think we should have two files in this repo: `readme.md` and `members.json` and call it MVP. Any progress we make on the `members.json` will contribute to saved time if we end up using a form later.

**Comment by DrewDahlman** [comment]
ship it.

**Comment by drewhutchison** [comment]
To clarify, does that exclude a json schema from MVP?

**Comment by aaronagray** [comment]
@drewhutchison My preference, which I believe @DrewDahlman was suggesting we ship, is to include the schema definition in the readme with contributor guidelines. I'm going to close this thread and start a second one for the schema format discussion now. Feel free to reopen if there's a misunderstanding though!
